version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    docker: # run the steps with Docker
      - image: adoptopenjdk:11
    jobs:
      - maven/test # checkout, build, test, and upload test results
